name: test-crush

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test-crush:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Prerequisites
        run: sudo apt-get update && sudo apt-get install -y curl ca-certificates gnupg

      - name: Configure crush (global)
        run: |
          mkdir -p ~/.config/crush
          cp ./crush.json ~/.config/crush/crush.json

      - name: Add Charm repo and install crush
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
          echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
          sudo apt-get update
          sudo apt-get install -y crush

      - name: Verify
        run: crush --version

      - name: Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Crush ping
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: crush run "Hi"

      - name: Implement + PR via Crush
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          crush run "
            Create and switch to branch crush/test-pr.
            Append the exact line 'Crush test' to the end of README.md.
            Run: git add README.md && git commit -m 'chore: add Crush test line'.
            Run: git push --set-upstream origin HEAD.
            Open a PR against main with: gh pr create --fill --base main --title 'Crush test PR' --body 'PR created by Crush'.
          "
