name: test-crush

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-crush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prerrequisitos
        run: sudo apt-get update && sudo apt-get install -y curl ca-certificates gnupg

      - name: Añadir repo de Charm e instalar crush
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
          echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
          sudo apt-get update
          sudo apt-get install -y crush

      - name: Verificar
        run: crush --version
