name: test-crush

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Crush prompt (use \\n for newlines)"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  test-crush:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Prerequisites
        run: sudo apt-get update && sudo apt-get install -y curl ca-certificates gnupg

      - name: Configure crush (global)
        run: |
          mkdir -p ~/.config/crush
          cp ./crush.json ~/.config/crush/crush.json

      - name: Add Charm repo and install crush
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
          echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
          sudo apt-get update
          sudo apt-get install -y crush

      - name: Verify
        run: crush --version

      - name: Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Implement + PR via Crush
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          crush run "Read and follow the Standing Orders in CRUSH.md. Task: $PROMPT"